/*
 * /*
Programmer: Kieren Foenander S012141776
Course: Object Oriented Programming COIT11134
Assignment 1
 */
package PWR;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author black
 */
public class CorePanel extends javax.swing.JPanel {

    /**
     * Creates new form CorePanel
     */
    public CorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coreLabel = new JLabel();
        teamLabel = new JLabel();
        partLabel = new JLabel();
        serialLabel = new JLabel();
        dateLabel = new JLabel();
        teamTextField = new JTextField();
        partNumberTextField = new JTextField();
        serialTextField = new JTextField();
        dayBox = new JComboBox<>();
        monthBox = new JComboBox<>();
        yearBox = new JComboBox<>();
        dayLabel = new JLabel();
        monthLabel = new JLabel();
        yearLabel = new JLabel();
        saveButton = new JButton();
        difLabel = new JLabel();
        jComboBox1 = new JComboBox<>();
        flatRadioButton = new JRadioButton();
        helixRadioButton = new JRadioButton();

        coreLabel.setFont(new Font("Dialog", 1, 24)); // NOI18N
        coreLabel.setText("Add Cores");
        coreLabel.setToolTipText("");

        teamLabel.setText("Team Name:");

        partLabel.setText("Part Number: ");

        serialLabel.setText("Serial: ");

        dateLabel.setText("Due Date:");

        dayBox.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthBox.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yearBox.setModel(new DefaultComboBoxModel<>(new String[] { "2020", "2021" }));

        dayLabel.setText("Day");

        monthLabel.setText("Month");

        yearLabel.setText("Year");

        saveButton.setText("Save");
        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        difLabel.setText("Core Difficulty level: ");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));

        flatRadioButton.setText("Flat Panel");
        flatRadioButton.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                flatRadioButtonItemStateChanged(evt);
            }
        });

        helixRadioButton.setText("Helix");
        helixRadioButton.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                helixRadioButtonItemStateChanged(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(coreLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(teamLabel)
                                    .addComponent(partLabel)
                                    .addComponent(serialLabel)
                                    .addComponent(dateLabel)
                                    .addComponent(difLabel))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(partNumberTextField)
                                    .addComponent(teamTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(flatRadioButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(helixRadioButton))
                                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(dayLabel)
                                                .addGap(12, 12, 12)
                                                .addComponent(dayBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(monthLabel)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(monthBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(yearLabel)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6))
                                    .addComponent(serialTextField))))))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(coreLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(teamLabel)
                    .addComponent(teamTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(partLabel)
                    .addComponent(partNumberTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(serialLabel)
                    .addComponent(serialTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(dayBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(monthBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(dayLabel)
                        .addComponent(monthLabel)
                        .addComponent(yearLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(flatRadioButton)
                    .addComponent(helixRadioButton))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(difLabel)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(saveButton)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void helixRadioButtonItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_helixRadioButtonItemStateChanged
        flatRadioButton.setSelected(false);
    }//GEN-LAST:event_helixRadioButtonItemStateChanged

    private void flatRadioButtonItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_flatRadioButtonItemStateChanged
        helixRadioButton.setSelected(false);
    }//GEN-LAST:event_flatRadioButtonItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel coreLabel;
    private JLabel dateLabel;
    private JComboBox<String> dayBox;
    private JLabel dayLabel;
    private JLabel difLabel;
    private JRadioButton flatRadioButton;
    private JRadioButton helixRadioButton;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> monthBox;
    private JLabel monthLabel;
    private JLabel partLabel;
    private JTextField partNumberTextField;
    private JButton saveButton;
    private JLabel serialLabel;
    private JTextField serialTextField;
    private JLabel teamLabel;
    private JTextField teamTextField;
    private JComboBox<String> yearBox;
    private JLabel yearLabel;
    // End of variables declaration//GEN-END:variables


    private void save(){
        String teamName;
        int partNumber;
        int Serial;
        int day;
        int month;
        int year; // declares variables to create a core object
        
    }
    
}
